"""create_recovery_tables

Revision ID: 18d2675de68c
Revises: 66fb07fd2172
Create Date: 2026-08-30 22:37:47.377338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18d2675de68c'
down_revision: Union[str, Sequence[str], None] = '66fb07fd2172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('max_incentive', sa.BigInteger(), nullable=False),
    sa.Column('max_exposure', sa.BigInteger(), nullable=False),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_exposure >= 0', name='chk_max_exposure_non_negative'),
    sa.CheckConstraint('max_incentive >= 0', name='chk_max_incentive_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_policies_merchant_id'), 'recovery_policies', ['merchant_id'], unique=False)
    op.create_table('recovery_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recovery_id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('selected_action', sa.String(length=50), nullable=False),
    sa.Column('incentive_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_amount', sa.BigInteger(), nullable=False),
    sa.Column('resulting_payment_id', sa.String(length=100), nullable=True),
    sa.CheckConstraint('incentive_amount >= 0', name='chk_incentive_amount_non_negative'),
    sa.CheckConstraint('recovered_amount >= 0', name='chk_recovered_amount_non_negative'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_incident_id'), 'recovery_attempts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_merchant_id'), 'recovery_attempts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_payment_id'), 'recovery_attempts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_recovery_id'), 'recovery_attempts', ['recovery_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_recovery_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_payment_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_merchant_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_incident_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index(op.f('ix_recovery_policies_merchant_id'), table_name='recovery_policies')
    op.drop_table('recovery_policies')
    # ### end Alembic commands ###
