"""add_payments_merchant_created_at_idx

Revision ID: 3cf01c72e62a
Revises: 4d042268caaa
Create Date: 2026-08-28 17:34:50.156555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf01c72e62a'
down_revision: Union[str, Sequence[str], None] = '4d042268caaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payments_merchant_id_created_at', 'payments', ['merchant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_merchant_id_created_at', table_name='payments')
    # ### end Alembic commands ###
