"""unique_payment_event_webhook_id

Revision ID: 4d042268caaa
Revises: 812a08801a33
Create Date: 2026-08-27 13:44:00.188176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d042268caaa'
down_revision: Union[str, Sequence[str], None] = '812a08801a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_webhook_event_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_webhook_event_id'), 'payment_events', ['webhook_event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_webhook_event_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_webhook_event_id'), 'payment_events', ['webhook_event_id'], unique=False)
    # ### end Alembic commands ###
