"""add_payment_link_cols_to_attempts

Revision ID: 78dd6ebeb951
Revises: 18d2675de68c
Create Date: 2026-08-30 22:45:18.859813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dd6ebeb951'
down_revision: Union[str, Sequence[str], None] = '18d2675de68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('payment_link_id', sa.String(length=100), nullable=True))
    op.add_column('recovery_attempts', sa.Column('short_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_recovery_attempts_payment_link_id'), 'recovery_attempts', ['payment_link_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_payment_link_id'), table_name='recovery_attempts')
    op.drop_column('recovery_attempts', 'short_url')
    op.drop_column('recovery_attempts', 'payment_link_id')
    # ### end Alembic commands ###
