"""associate webhook events with merchants

Revision ID: 812a08801a33
Revises: cccc089e89d7
Create Date: 2026-08-26 22:25:35.985787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812a08801a33'
down_revision: Union[str, Sequence[str], None] = 'cccc089e89d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_events', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'webhook_events', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_column('webhook_events', 'merchant_id')
    # ### end Alembic commands ###
