"""add_decision_evidence

Revision ID: 89aff5fc5ca0
Revises: 78dd6ebeb951
Create Date: 2026-08-31 11:29:07.016308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aff5fc5ca0'
down_revision: Union[str, Sequence[str], None] = '78dd6ebeb951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_webhook_event_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_webhook_event_id'), 'payment_events', ['webhook_event_id'], unique=False)
    op.add_column('recovery_attempts', sa.Column('decision_evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_attempts', 'decision_evidence')
    op.drop_index(op.f('ix_payment_events_webhook_event_id'), table_name='payment_events')
    op.create_index(op.f('ix_payment_events_webhook_event_id'), 'payment_events', ['webhook_event_id'], unique=True)
    # ### end Alembic commands ###
