"""create_recovery_campaigns_table

Revision ID: a1ceb094e27c
Revises: 89aff5fc5ca0
Create Date: 2026-09-01 12:33:48.872230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ceb094e27c'
down_revision: Union[str, Sequence[str], None] = '89aff5fc5ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('selected_action', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('target_payment_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('per_attempt_incentive', sa.BigInteger(), nullable=False),
    sa.Column('total_incentive_cost', sa.BigInteger(), nullable=False),
    sa.Column('decision_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('per_attempt_incentive >= 0', name='chk_campaign_per_attempt_incentive_non_negative'),
    sa.CheckConstraint('target_payment_count >= 0', name='chk_campaign_target_count_non_negative'),
    sa.CheckConstraint('total_incentive_cost >= 0', name='chk_campaign_total_incentive_non_negative'),
    sa.CheckConstraint('total_revenue_at_risk >= 0', name='chk_campaign_revenue_risk_non_negative'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_campaigns_campaign_id'), 'recovery_campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_recovery_campaigns_incident_id'), 'recovery_campaigns', ['incident_id'], unique=False)
    op.create_index(op.f('ix_recovery_campaigns_merchant_id'), 'recovery_campaigns', ['merchant_id'], unique=False)
    op.add_column('recovery_attempts', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_recovery_attempts_campaign_id'), 'recovery_attempts', ['campaign_id'], unique=False)
    op.create_foreign_key('fk_recovery_attempts_campaign_id', 'recovery_attempts', 'recovery_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recovery_attempts_campaign_id', 'recovery_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_recovery_attempts_campaign_id'), table_name='recovery_attempts')
    op.drop_column('recovery_attempts', 'campaign_id')
    op.drop_index(op.f('ix_recovery_campaigns_merchant_id'), table_name='recovery_campaigns')
    op.drop_index(op.f('ix_recovery_campaigns_incident_id'), table_name='recovery_campaigns')
    op.drop_index(op.f('ix_recovery_campaigns_campaign_id'), table_name='recovery_campaigns')
    op.drop_table('recovery_campaigns')
    # ### end Alembic commands ###
