"""create_incidents_table

Revision ID: f4034af01c2d
Revises: 3cf01c72e62a
Create Date: 2026-08-30 22:01:23.398543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4034af01c2d'
down_revision: Union[str, Sequence[str], None] = '3cf01c72e62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('error_step', sa.String(length=100), nullable=False),
    sa.Column('current_total_count', sa.Integer(), nullable=False),
    sa.Column('current_failed_count', sa.Integer(), nullable=False),
    sa.Column('current_failure_rate', sa.Float(), nullable=False),
    sa.Column('current_total_amount', sa.BigInteger(), nullable=False),
    sa.Column('current_failed_amount', sa.BigInteger(), nullable=False),
    sa.Column('baseline_total_count', sa.Integer(), nullable=False),
    sa.Column('baseline_failed_count', sa.Integer(), nullable=False),
    sa.Column('baseline_failure_rate', sa.Float(), nullable=False),
    sa.Column('baseline_total_amount', sa.BigInteger(), nullable=False),
    sa.Column('baseline_failed_amount', sa.BigInteger(), nullable=False),
    sa.Column('absolute_rate_increase', sa.Float(), nullable=False),
    sa.Column('relative_degradation', sa.Float(), nullable=False),
    sa.Column('revenue_at_risk', sa.BigInteger(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_merchant_id'), 'incidents', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_merchant_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
